# Generated by Django 2.1.5 on 2019-03-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='writersapp.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=100),
        ),
    ]
